export const tags = [
  "React",
  "Angular",
  "Next",
  "JavaScript",
  "TypeScript",
  "Tailwind",
  "Figma",
  "Node.js",
  "Express.js",
  "Vue.js",
  "Svelte",
  "Redux",
  "GraphQL",
  "REST API",
  "MongoDB",
  "SQL",
  "Firebase",
  "AWS",
  "Docker",
  "Kubernetes",
  "Jest",
  "Cypress",
  "Webpack",
  "Babel",
  "HTML5",
  "CSS3",
  "SASS",
  "Bootstrap",
  "Material-UI",
  "Ant Design",
];

export const ADD_TAGS_GITHUB_URL = `https://github.com/JAYKALIA007/galleria/blob/master/app/react-snippets/add-tags/AddTags.tsx`;
